//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace управление_проектами
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class ассортимент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ассортимент()
        {
            this.заказ = new HashSet<заказ>();
        }
        public string GetPhoto
        {
            get
            {
                if (фото is null)
                    return Directory.GetCurrentDirectory() + @"\Images\";
                return Directory.GetCurrentDirectory() + @"\Images\picture.png";
                    
            }
        }

        public int ID_товара { get; set; }
        public string название { get; set; }
        public byte[] фото { get; set; }
        public double длина { get; set; }
        public double ширина { get; set; }
        public int пряжа { get; set; }
        public int ткань { get; set; }
        public double цена { get; set; }
    
        public virtual запас_пряжи запас_пряжи { get; set; }
        public virtual запас_ткани запас_ткани { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<заказ> заказ { get; set; }
    }
}
