//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace управление_проектами
{
    using System;
    using System.Collections.Generic;
    
    public partial class запас_пряжи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public запас_пряжи()
        {
            this.ассортимент = new HashSet<ассортимент>();
        }
    
        public int ID_пряжи { get; set; }
        public string название { get; set; }
        public double цена_за_метр { get; set; }
        public string цвет { get; set; }
        public double количество { get; set; }
        public string плотность { get; set; }
        public string основной_состав { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ассортимент> ассортимент { get; set; }
    }
}
