//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace управление_проектами
{
    using System;
    using System.Collections.Generic;
    
    public partial class заказ
    {
        public int ID_заказа { get; set; }
        public int клиент { get; set; }
        public int работник { get; set; }
        public int товар { get; set; }
        public System.DateTime дата_заказа { get; set; }
    
        public virtual ассортимент ассортимент { get; set; }
        public virtual клиенты клиенты { get; set; }
        public virtual работники работники { get; set; }
    }
}
