//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace управление_проектами
{
    using System;
    using System.Collections.Generic;
    
    public partial class клиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public клиенты()
        {
            this.заказ = new HashSet<заказ>();
        }
    
        public int ID_клиента { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public string номер_телефона { get; set; }
        public string город_доставки { get; set; }
        public string улица_доставки { get; set; }
        public string дом_доставки { get; set; }
        public string квартира_доставки { get; set; }
        public int количество_купленных_товаров { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<заказ> заказ { get; set; }
    }
}
