//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace управление_проектами
{
    using System;
    using System.Collections.Generic;
    
    public partial class работники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public работники()
        {
            this.заказ = new HashSet<заказ>();
        }
    
        public int ID_работника { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public string серия_номер_паспорта { get; set; }
        public System.DateTime дата_рождения { get; set; }
        public string пол { get; set; }
        public string должность { get; set; }
        public string квалификация { get; set; }
        public string номер_телефона { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<заказ> заказ { get; set; }
    }
}
